# Generated by Django 4.1.7 on 2023-05-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='offer',
            field=models.ManyToManyField(through='main.CVResponse', to='main.offer'),
        ),
    ]
