# Generated by Django 4.1.7 on 2023-04-15 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvresponse',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='offerresponse',
            name='seeker',
        ),
        migrations.AlterField(
            model_name='offer',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city'),
        ),
    ]
