# Generated by Django 4.1.7 on 2023-04-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_cvresponse_employer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerresponse',
            name='letter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
