# Generated by Django 4.1.7 on 2023-05-29 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cv_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='offer',
            new_name='offers',
        ),
    ]
