# Generated by Django 4.1.7 on 2023-04-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_offerresponse_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='offer',
            field=models.ManyToManyField(related_name='offer_response', through='main.OfferResponse', to='main.offer'),
        ),
        migrations.AddField(
            model_name='offer',
            name='cv',
            field=models.ManyToManyField(related_name='cv_response', through='main.CVResponse', to='main.cv'),
        ),
    ]
